name: laza
description: "e-commerce App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  #state management
  flutter_bloc: ^8.1.2

  #local database
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  build_runner: ^2.0.0
  equatable: ^2.0.7
  http: ^1.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

